# docker-compose.yml
services:
  influxdb3-explorer:
    image: influxdata/influxdb3-ui:latest
    container_name: influxdb3-explorer
    hostname: influxdb3-explorer-local
    ports:
      - "8888:80"
    networks:
      - develop-network
    volumes:
      - influxdb3-explorer-data:/db
      - ./config:/app-root/config:ro
      - ./ssl:/etc/nginx/ssl:ro
      - ./ca-certs:/ca-certs:ro
    restart: unless-stopped
    command: ["--mode=admin"]

networks:
  develop-network:
    external: true
    name: develop

volumes:
  influxdb3-explorer-data:
    name: influxdb3-explorer-data
