name: Push otel-collector-service on pull request

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
    paths:
      - .github/workflows/otel-collector-service-test.yml
      - otel-collector-service/config.yaml
      - otel-collector-service/Dockerfile
      - otel-collector-service/version.yaml

env:
  REGISTRY: davgeoand9
  REPOSITORY: otel-collector-service
  AWS_REGION: us-east-1
  ECS_TASK_DEFINITION: otel-collector-service-test
  ECS_TASK_DEFINITION_FILE: task-definition.json
  ECS_CLUSTER: homeproject-services-test-ecs-cluster

jobs:
  build:
    runs-on: ubuntu-latest
    environment: test

    steps:
      - uses: actions/checkout@v4

      - name: Get otel collector version
        id: lookupOtelCollectorVersion
        uses: mikefarah/yq@master
        with:
          cmd: yq '.otel-collector-contrib.version' 'otel-collector-service/version.yaml'

      - name: docker login
        run: |
          docker login -u $REGISTRY -p ${{secrets.DOCKER_PASSWORD}}

      - name: Push the Docker image
        id: push-image
        run: |
          bash docker_image.sh $REPOSITORY test ${{ steps.lookupOtelCollectorVersion.outputs.result }} ${GITHUB_SHA::7}

      - name: Configure AWS Creds
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Download task definition
        run: |
          aws ecs describe-task-definition --task-definition ${{ env.ECS_TASK_DEFINITION }} --query taskDefinition > ${{ env.ECS_TASK_DEFINITION_FILE }}

      - name: Fill in the new image ID in the Amazon ECS task definition
        id: task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: ${{ env.ECS_TASK_DEFINITION_FILE }}
          container-name: ${{ env.REPOSITORY }}
          image: ${{ steps.push-image.outputs.image }}

      - name: Deploy Amazon ECS task definition
        uses: aws-actions/amazon-ecs-deploy-task-definition@v2
        with:
          task-definition: ${{ steps.task-def.outputs.task-definition }}
          service: ${{ env.REPOSITORY }}
          cluster: ${{ env.ECS_CLUSTER }}
          wait-for-service-stability: true